---

- include_tasks: gateway_id.yml

- name: create Direct Connect Gateway
  aws_direct_connect_gateway:
    amazon_asn: '{{ aws_directconnect_gateway_asn }}'
    name: '{{ aws_directconnect_gateway_name }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_directconnect_gateway
  when: _aws_directconnect_gateway_id == ''

- name: set Direct Connect Gateway ID fact
  set_fact:
    _aws_directconnect_gateway_id:
      '{{ _aws_directconnect_gateway.direct_connect_gateway_id }}'
  when: _aws_directconnect_gateway is changed
