---

- name: list existing virtual interfaces
  command: >
    aws directconnect describe-virtual-interfaces
                      --profile '{{ aws_profile }}'
                      --query 'virtualInterfaces[? virtualInterfaceState
                                                   != `deleted`]'
  register: _aws_directconnect_existing_vifs_command
  changed_when: False

- name: initialize existing virtual interfaces fact
  set_fact:
    _aws_directconnect_existing_vifs: {}

- name: set existing virtual interfaces fact
  set_fact:
    _aws_directconnect_existing_vifs: >
      {{ _aws_directconnect_existing_vifs
         | combine({item.virtualInterfaceName: item}) }}
  with_items: >
    {{ _aws_directconnect_existing_vifs_command.stdout | from_json }}
  no_log: True
